from __future__ import annotations

import json
import re

from .filesystem_component import FilesystemComponent


def _snake_case(value: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9]+", "_", value)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_").lower()
    return cleaned or "tool"


def _pascal_case(value: str) -> str:
    parts = [part for part in re.split(r"[^a-zA-Z0-9]+", value) if part]
    return "".join(part[:1].upper() + part[1:] for part in parts) or "Tool"


class ScaffoldComponent:
    """Owns manifest-driven scaffolding and self-tool skeleton generation."""

    def __init__(self, filesystem_component: FilesystemComponent) -> None:
        self._filesystem_component = filesystem_component

    def scaffold_from_manifest(
        self,
        directories: list[str],
        files: list[dict[str, str]],
        mode: str = "create_only",
    ) -> dict[str, object]:
        directory_result = self._filesystem_component.make_tree(directories)
        file_result = self._filesystem_component.write_files(files, mode=mode)
        return {
            "directories": directory_result,
            "files": file_result,
        }

    def create_tool_scaffold(
        self,
        tool_name: str,
        description: str,
        manager: str,
        action: str,
    ) -> dict[str, object]:
        safe_name = _snake_case(tool_name)
        class_name = f"{_pascal_case(tool_name)}Component"
        method_name = _snake_case(action)
        module_path = f"src/core/components/extensions/{safe_name}_component.py"
        test_path = f"tests/generated/test_{safe_name}.py"
        blueprint_json_path = f"_docs/tool_blueprints/{safe_name}.json"
        blueprint_md_path = f"_docs/tool_blueprints/{safe_name}.md"

        files = [
            {
                "path": "src/core/components/extensions/__init__.py",
                "content": '"""Extension component stubs generated by the worker."""\n',
            },
            {
                "path": module_path,
                "content": self._render_component_stub(
                    class_name=class_name,
                    method_name=method_name,
                    description=description,
                    tool_name=tool_name,
                ),
            },
            {
                "path": test_path,
                "content": self._render_test_stub(class_name=class_name, module_path=module_path),
            },
            {
                "path": blueprint_json_path,
                "content": json.dumps(
                    {
                        "tool_name": tool_name,
                        "description": description,
                        "manager": manager,
                        "action": action,
                        "method_name": method_name,
                        "component_module": module_path.replace("/", ".").removesuffix(".py"),
                        "component_class": class_name,
                        "input_schema": {
                            "type": "object",
                            "properties": {},
                            "additionalProperties": True,
                        },
                        "status": "draft",
                        "integration_touchpoints": [
                            "src/core/orchestrators/mcp_orchestrator.py",
                            f"src/core/managers/{manager}_manager.py",
                            "_docs/TOOLS.md",
                        ],
                    },
                    indent=2,
                )
                + "\n",
            },
            {
                "path": blueprint_md_path,
                "content": self._render_blueprint_markdown(
                    tool_name=tool_name,
                    description=description,
                    manager=manager,
                    action=action,
                    module_path=module_path,
                    class_name=class_name,
                    test_path=test_path,
                ),
            },
        ]

        result = self._filesystem_component.write_files(files, mode="create_only")
        return {
            "tool_name": tool_name,
            "manager": manager,
            "action": action,
            "generated_files": (
                result["created_files"] + result["updated_files"] + result["skipped_files"]
            ),
            "next_steps": [
                "Implement the generated component stub.",
                "Run worker.refresh_extension_tools to hot-load the blueprint once the stub is ready.",
                f"Optionally promote the tool into a static route later if it graduates beyond extension status.",
                "Add or refine the generated test stub.",
                "Restart only if you want to verify bootstrap-time loading as well.",
            ],
        }

    def _render_component_stub(
        self,
        class_name: str,
        method_name: str,
        description: str,
        tool_name: str,
    ) -> str:
        return (
            "from __future__ import annotations\n\n\n"
            f"class {class_name}:\n"
            f"    \"\"\"{description}\"\"\"\n\n"
            f"    def {method_name}(self, arguments: dict[str, object]) -> dict[str, object]:\n"
            f"        \"\"\"Implement the '{tool_name}' tool here.\"\"\"\n\n"
            "        return {\n"
            '            "status": "todo",\n'
            '            "message": "Tool stub created but not implemented yet.",\n'
            "            \"arguments\": arguments,\n"
            "        }\n"
        )

    def _render_test_stub(self, class_name: str, module_path: str) -> str:
        module_import = module_path.replace("/", ".").removesuffix(".py")
        return (
            "from __future__ import annotations\n\n"
            "import unittest\n\n"
            f"from {module_import} import {class_name}\n\n\n"
            f"class {class_name}Tests(unittest.TestCase):\n"
            "    def test_component_stub_is_instantiable(self) -> None:\n"
            f"        component = {class_name}()\n"
            "        self.assertIsNotNone(component)\n"
        )

    def _render_blueprint_markdown(
        self,
        tool_name: str,
        description: str,
        manager: str,
        action: str,
        module_path: str,
        class_name: str,
        test_path: str,
    ) -> str:
        return "\n".join(
            [
                f"# Tool Blueprint: {tool_name}",
                "",
                "## Description",
                "",
                description,
                "",
                "## Route",
                "",
                f"- Manager: `{manager}`",
                f"- Action: `{action}`",
                f"- Method: `{_snake_case(action)}`",
                "- Hot-load path: `worker.refresh_extension_tools`",
                "",
                "## Generated Files",
                "",
                f"- `{module_path}`",
                f"- `{test_path}`",
                f"- `{class_name}`",
                "",
                "## Integration Touchpoints",
                "",
                "- `src/core/orchestrators/mcp_orchestrator.py`",
                f"- `src/core/managers/{manager}_manager.py`",
                "- `_docs/TOOLS.md`",
                "",
            ]
        ) + "\n"
